services:
  app:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      DB_SERVER: ""
      DB_USER: ""
      DB_PASSWORD: ""
      DB_NAME: ""
    restart: unless-stopped
